### ISSUE TITLE
Android 8 (Oreo) fatal exception

### ISSUE THREAD

**Issue by roktoshl** [BatchLabs/android-sdk#1]
When using Batch sdk (1.10.0) with Android API 26 I get the following error:

java.lang.RuntimeException: Unable to start receiver com.batch.android.BatchPushReceiver: java.lang.IllegalStateException: Not allowed to start service Intent

Perhaps you need to change the Intent to JobServiceIntent, since Android 8 has some background limitations.

**Comment by abarisain** [comment]
Hi,

When exactly does that happen? Do you have a way to reproduce it?

**Comment by roktoshl** [comment]
It actually happens when I send a push notification through Firebase. I don't know how is that connected though.

**Comment by abarisain** [comment]
Okay thanks, we'll look into it anyway. Maybe it has to do with the GCM priority used.

This issue has not shown up during our O testing phase, but we've planned to experiment again with JobScheduler.enqueue. Our previous tests had shown that notifications showed up late or sometimes not at all, but that was during the developer beta.

**Comment by roktoshl** [comment]
@abarisain Thank you for the quick reply!

**Comment by abarisain** [comment]
I confirm that this only occurs when pushing in normal FCM priority: Pushing with High temporarily whitelists the application from background restrictions

**Comment by roktoshl** [comment]
Hey @abarisain thanks for the quick bug location, will you submit a patch for this in the next update?

**Comment by abarisain** [comment]
Yes, we're working on a hotfix as we speak.

**Comment by abarisain** [comment]
Hello!

We just released Batch SDK 1.10.1, which switches to a JobService when appropriate. This should fix your issue.

**Comment by roktoshl** [comment]
@abarisain Yes i can confirm it works now, thanks!
