### ISSUE TITLE
SQLiteConnection object was leaked

### ISSUE THREAD

**Issue by roktoshl** [BatchLabs/android-sdk#2]
Hy i'm reporting an issue found from logging my Android app, it seems like there is a database leak:

01-17 00:08:58.880 D/Batch (25367): Batch.Push: Registration id: cMCRw8f1RDA:APA91bESs-ZveXFDW3QvxHS3kGd303m5wntRuGJOf4a_IHcL2eXUE9YcIG28sUltCVO-W2nWhwpj46l7nPoNVaNZFJDzBc9vY343LZEc2JrW3T-uN2YnOFDuXtgKYNrppwIPeQSeprOH
01-17 00:08:59.729 W/SQLiteConnectionPool(25367): A SQLiteConnection object for database '/data/user/0/com.thirdframestudios.android.expensoor/databases/ba_tr.db' was leaked! Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.

01-17 00:01:34.867 W/SQLiteConnectionPool(25367): A SQLiteConnection object for database '/data/user/0/com.thirdframestudios.android.expensoor/databases/ba_tr.db' was leaked! Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.

**Comment by abarisain** [comment]
Hello and thanks for the report.

Unfortunately it seems to be a false positive. We close the databases when necesarry, but then can outlive activities for various reasons, as Batch works more on an app level than an activity one.  The connection isn't actually leaked, but still used.
